### ISSUE TITLE
Have issues with Language.py 

### ISSUE THREAD

**Issue by Deva09876** [Pranav-Saraswat/AnonXMusicFork#24]
Files using language have issue. App doesn't send or reply to any command.

**Comment by Pranav-Saraswat** [comment]
@Deva09876 what do you mean?

**Comment by Deva09876** [comment]
Deploy The Bot And Start It. You'll Get To Know The Error.

Else Give Your Telegram Username So That I Can Give You Ss.

**Comment by Pranav-Saraswat** [comment]
can you send me the logs that what issue are you facing then I'll try to fix it asap

**Comment by Deva09876** [comment]
![IMG_20231130_225924_392](https://github.com/Pranav-Saraswat/Testing-Alpha1/assets/125013272/44838542-2e51-440b-8e80-94f29330c86c)

**Comment by Pranav-Saraswat** [comment]
I'll see this error later

**Comment by Deva09876** [comment]
![IMG_20231202_000905_743](https://github.com/Pranav-Saraswat/Testing-Alpha1/assets/125013272/0f22ce34-d94b-43d0-928d-c38544852d03)

What About This?

**Comment by Deva09876** [comment]
@ITZ-ZAID 
Using The Same Repo And py-tgcalls version in up-to-date.

**Comment by ITZ-ZAID** [comment]
@Deva09876 pip3 install py-tgcalls==1.0.3
