### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ItzMeRadha** [Pranav-Saraswat/AnonXMusicFork#33]
Why showing this error after 30-40 min?

ERROR: unable to open for writing: [Errno 24] Too many open files: 'downloads/j0
hRGBUtAPA.webm.part'
[Errno 24] Too many open files: 'cache/thumbZgP8UC24HLo.png'
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x7faa82219b
40>: Failed to establish a new connection: [Errno 24] Too many open files
[err] evsignal_init: socketpair: Too many open files
root@vps:~/AnonXMusic#

**Comment by Pranav-Saraswat** [comment]
@annihilatorrrr you know anything about this error?

**Comment by Pranav-Saraswat** [comment]
seems like there is an issue in socket pairing

**Comment by annihilatorrrr** [comment]
yeah i too get in my vps using, try using stable version of python i assume u ar using python 3.11 (dev)
